mo.rpc.run:
    path: /run/{service}/{method}
    methods: [GET]
    defaults: { _controller: RPCBundle:RPC:run, service: null, method: null }


mo.rpc.documentation:
    path: /documentation
    methods: [GET]
    defaults: { _controller: RPCBundle:RPC:documentation }
